/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NDocLog {
    }
}
declare global {
    interface HTMLNDocLogElement extends Components.NDocLog, HTMLStencilElement {
    }
    var HTMLNDocLogElement: {
        prototype: HTMLNDocLogElement;
        new (): HTMLNDocLogElement;
    };
    interface HTMLElementTagNameMap {
        "n-doc-log": HTMLNDocLogElement;
    }
}
declare namespace LocalJSX {
    interface NDocLog {
    }
    interface IntrinsicElements {
        "n-doc-log": NDocLog;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "n-doc-log": LocalJSX.NDocLog & JSXBase.HTMLAttributes<HTMLNDocLogElement>;
        }
    }
}
