/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NDocLog {
    }
    interface NDocSource {
        /**
          * The source file line-number to start with
         */
        "from": number;
        /**
          * The markdown language to use
         */
        "language": 'html' | 'jsx';
        /**
          * Cross Origin Mode
         */
        "mode": 'cors' | 'navigate' | 'no-cors' | 'same-origin';
        /**
          * Remote Template URL
         */
        "src": string;
        /**
          * The source file line number to end with
         */
        "to"?: number;
    }
}
declare global {
    interface HTMLNDocLogElement extends Components.NDocLog, HTMLStencilElement {
    }
    var HTMLNDocLogElement: {
        prototype: HTMLNDocLogElement;
        new (): HTMLNDocLogElement;
    };
    interface HTMLNDocSourceElement extends Components.NDocSource, HTMLStencilElement {
    }
    var HTMLNDocSourceElement: {
        prototype: HTMLNDocSourceElement;
        new (): HTMLNDocSourceElement;
    };
    interface HTMLElementTagNameMap {
        "n-doc-log": HTMLNDocLogElement;
        "n-doc-source": HTMLNDocSourceElement;
    }
}
declare namespace LocalJSX {
    interface NDocLog {
    }
    interface NDocSource {
        /**
          * The source file line-number to start with
         */
        "from"?: number;
        /**
          * The markdown language to use
         */
        "language"?: 'html' | 'jsx';
        /**
          * Cross Origin Mode
         */
        "mode"?: 'cors' | 'navigate' | 'no-cors' | 'same-origin';
        /**
          * Remote Template URL
         */
        "src": string;
        /**
          * The source file line number to end with
         */
        "to"?: number;
    }
    interface IntrinsicElements {
        "n-doc-log": NDocLog;
        "n-doc-source": NDocSource;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "n-doc-log": LocalJSX.NDocLog & JSXBase.HTMLAttributes<HTMLNDocLogElement>;
            "n-doc-source": LocalJSX.NDocSource & JSXBase.HTMLAttributes<HTMLNDocSourceElement>;
        }
    }
}
