name: main-publish
on:
  push:
    branches:
      - main
    tags:
      - '*'
    
permissions:
  contents: write

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
    outputs:
      url: ${{ steps.release.outputs.url }}

  announce:
    name: Announce
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v3
        name: checkout
        with:
          fetch-depth: 0
      - name: version
        uses: damienaicheh/extract-version-from-tag-action@v1.0.0
        if: startsWith(github.ref, 'refs/tags/')
      - name: twitter
        uses: mugi111/tweet-trigger-release@v1.1
        with:
          consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          access_token_key: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          tweet_body: |
            NENT v$MAJOR.$MINOR.$PATCH Published
            Get the latest here:
            https://www.npmjs.com/package/@nent/core
