name: release

on:
  push:
    branches:
      - main
    tags:
      - '**'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: Extract Version
        uses: damienaicheh/extract-version-from-tag-action@v1.0.0
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
      - name: Tweet
        uses: mugi111/tweet-trigger-release@v1.1
        with:
          consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          access_token_key: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          tweet_body: |-
            New NENT $MAJOR.$MINOR.$PATCH Published!
            https://github.com/nent/nent/releases/tag/$MAJOR.$MINOR.$PATCH 
